[technote]
id = "SITCOMTN-162"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-162.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-162"
github_default_branch = "main"
date_created = 2025-06-25T17:43:51Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
internal_id = "gorsuchmr"
orcid = "https://orcid.org/0000-0002-3135-3824"
name = {given = "Miranda R.", family = "Gorsuch"}
[[technote.authors.affiliations]]
name = "University of Wisconsin-Madison"
internal_id = "WisconsinMadison"
address = "University of Wisconsin-Madison, Madison, WI 53706, USA"
ror = "https://ror.org/01y2jtd41"
[[technote.authors]]
name = {given = "Arun", family = "Kannawadi"}
internal_id = "kannawadia"
orcid = "https://orcid.org/0000-0001-8783-6529"
[[technote.authors.affiliations]]
name = "Duke University"
internal_id = "Duke"
ror = "https://ror.org/00py81415"
[[technote.authors.affiliations]]
name = "Princeton University"
internal_id = "Princeton-Astro"
ror = "https://ror.org/00hx57361"
[[technote.authors]]
name = {given = "Prakruth", family = "Adari"}
internal_id = "adarip"
orcid = "https://orcid.org/0000-0001-9431-3806"
[[technote.authors.affiliations]]
name = "Stony Brook University"
internal_id = "StonyBrookU"
ror = "https://ror.org/05qghxh33"
[[technote.authors]]
name = {given = "Anthony", family = "Englert"}
internal_id = "englerta"
orcid = "https://orcid.org/0000-0003-2314-5336"
[[technote.authors.affiliations]]
name = "Brown University"
internal_id = "Brown"
ror = "https://ror.org/05gq02987"
[[technote.authors]]
name = {given = "Matthew R.", family = "Becker"}
internal_id = "beckermr"
orcid = "https://orcid.org/0000-0001-7774-2246"
[[technote.authors.affiliations]]
name = "Argonne National Laboratory"
internal_id = "ANL-HEP"
ror = "https://ror.org/05gvnxz63"
[[technote.authors]]
name = {given = "Céline", family = "Combet"}
internal_id = "combetc"
orcid = "https://orcid.org/0000-0001-6487-1866"
[[technote.authors.affiliations]]
name = "Université Grenoble Alpes, CNRS/IN2P3, LPSC"
internal_id = "IN2P3-LPSC"
ror = "https://ror.org/03f0apy98"
[[technote.authors]]
name = {given = "Axel", family = "Guinot"}
internal_id = "guinota"
orcid = "https://orcid.org/0000-0002-5068-7918"
[[technote.authors.affiliations]]
name = "Carnegie Mellon University"
internal_id = "CMU"
ror = "https://ror.org/05x2bcf33"
[[technote.authors]]
name = {given = "Rachel", family = "Mandelbaum"}
internal_id = "mandelbaumr"
orcid = "https://orcid.org/0000-0003-2271-1527"
[[technote.authors.affiliations]]
name = "Carnegie Mellon University"
internal_id = "CMU"
ror = "https://ror.org/05x2bcf33"
[[technote.authors]]
name = {given = "Sidney", family = "Mau"}
internal_id = "maus"
orcid = "https://orcid.org/0000-0003-3519-4004"
[[technote.authors.affiliations]]
name = "Duke University"
internal_id = "Duke"
ror = "https://ror.org/00py81415"
[[technote.authors]]
name = {given = "Eske M.", family = "Pedersen"}
internal_id = "pedersene"
orcid = "https://orcid.org/0000-0002-8883-2172"
[[technote.authors.affiliations]]
name = "Harvard University"
internal_id = "Harvard-Physics"
ror = "https://ror.org/03vek6s52"
[[technote.authors]]
name = {given = "Anja", family = "von der Linden"}
internal_id = "lindena"
orcid = "https://orcid.org/0000-0002-3881-7724"
[[technote.authors.affiliations]]
name = "Stony Brook University"
internal_id = "StonyBrookU"
ror = "https://ror.org/05qghxh33"
